name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test vercel-wait
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run vercel-wait
        id: vercel-wait
        uses: ./
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          sha: 5d2feda3b25c47193f6339938b06945f1b1a23f2
      - name: Show output
        run: |
          echo '${{ toJSON(steps.vercel-wait.outputs) }}'
        shell:
          bash
