name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test vercel-wait
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run vercel-wait
        id: vercel-wait
        uses: ./
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          sha: 7fc25ddc858357579d0136448c3470c1c9a37b66
      - name: Show output
        run: |
          echo '${{ toJSON(steps.vercel-wait.outputs) }}'
        shell:
          bash
