name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test vercel-wait
    if: |
      github.actor != 'dependabot[bot]' ||
      github.actor != 'dependabot' ||
      github.actor != 'dependabot-preview[bot]' ||
      github.actor != 'dependabot-preview' ||
      github.actor != 'renovate[bot]' ||
      github.actor != 'renovate'
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run vercel-wait
        id: vercel-wait
        uses: ./
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          sha: 298d2319936ddcd63b3027276d3ab00ef1709520
      - name: Show output
        run: |
          echo '${{ toJSON(steps.vercel-wait.outputs) }}'
        shell:
          bash
